config/routes.rb
Sufia::Engine.routes.draw do
  get 'single_use_link/generate_download/:id' => 'single_use_links#new_download', :as => :generate_download_single_use_link
  get 'single_use_link/generate_show/:id' => 'single_use_links#new_show', :as => :generate_show_single_use_link
  get 'single_use_link/show/:id' => 'single_use_links_viewer#show', :as => :show_single_use_link
  get 'single_use_link/download/:id' => 'single_use_links_viewer#download', :as => :download_single_use_link

  match 'batch_edits/clear' => 'batch_edits#clear', :as => :batch_edits_clear, via: [:get, :post]

  # Route path-less requests to the index view of catalog
  root :to => "catalog#index"
  
  # "Recently added files" route for catalog index view
  get "catalog/recent" => "catalog#recent", :as => :catalog_recent

  # "Notifications" route for catalog index view
  get "users/notifications_number" => "users#notifications_number", :as => :user_notify

  # Generic file routes
  resources :generic_files, :path => :files, :except => :index do
    member do
      get 'citation', :as => :citation
      post 'audit'
    end
  end

  # Downloads controller route
  resources :downloads, :only => "show"

  # Messages
  get 'notifications' => 'mailbox#index', :as => :mailbox
  match 'notifications/delete_all' => 'mailbox#delete_all', as: :mailbox_delete_all, via: [:get, :post]
  match 'notifications/:uid/delete' => 'mailbox#delete', as: :mailbox_delete, via: [:get, :post]

  # User profile & follows
  resources :users, only: [:index, :show, :edit, :update], as: :profiles
  # get 'users' => 'users#index', :as => :profiles
  # get 'users/:uid' => 'users#show', :as => :profile
  # get 'users/:uid/edit' => 'users#edit', :as => :edit_profile
  # put 'users/:uid/update' => 'users#update', :as => :update_profile
  post "users/:id/trophy" => "users#toggle_trophy", :as => :update_trophy_user
  match 'users/:id/follow' => 'users#follow', :as => :follow_user, via: [:get, :post]
  match 'users/:id/unfollow' => 'users#unfollow', :as => :unfollow_user, via: [:get, :post]

  # Dashboard routes (based partly on catalog routes)
  resources 'dashboard', :only=>:index do
    collection do
      get 'page/:page', :action => :index
      get 'activity', :action => :activity, :as => :dashboard_activity
      get 'facet/:id', :action => :facet, :as => :dashboard_facet
    end
  end
    

  # advanced routes for advanced search
  get 'search' => 'advanced#index', :as => :advanced

  # Authority vocabulary queries route
  get 'authorities/:model/:term' => 'authorities#query'

  # LDAP-related routes for group and user lookups
  get 'directory/user/:uid' => 'directory#user'
  get 'directory/user/:uid/:attribute' => 'directory#user_attribute'
  get 'directory/group/:cn' => 'directory#group', :constraints => { :cn => /.*/ }

  # Batch edit routes
  get 'batches/:id/edit' => 'batch#edit', :as => :batch_edit
  post 'batches/:id/' => 'batch#update', :as => :batch_generic_files

  # Contact form routes
  post 'contact' => 'contact_form#create', :as => :contact_form_index
  get 'contact' => 'contact_form#new'

  # Resque monitoring routes. Don't bother with this route unless Sufia::ResqueAdmin
  # has been defined in the initalizers.
  if defined?(Sufia::ResqueAdmin)
    namespace :admin do
      constraints Sufia::ResqueAdmin do
        mount Resque::Server, :at => "queues"
      end
    end
  end

  # Static page routes (workaround)
  get ':action' => 'static#:action', :constraints => { :action => /about|help|terms|zotero|mendeley|agreement|subject_libraries|versions/ }, :as => :static

  #Single use link errors
  get 'single_use_link/not_found' => 'errors#single_use_error'
  get 'single_use_link/expired' => 'errors#single_use_error'

  # Catch-all (for routing errors)
  unless Rails.env.development? || Rails.env.test?
    match '*error' => 'errors#routing', via: [:get, :post]
  end
  
end

app/views/catalog/_bookmark_form.html.erb
<%= form_tag '/bookmarks', :name => "bookmarks" do %>
  <% documents.each_with_index do |document, index| %>
    <%= hidden_field_tag "bookmarks[#{index}][document_id]", document.get(:id)%>
    <%= hidden_field_tag "bookmarks[#{index}][title]", h(document[document_show_link_field])%>
  <% end %>
  <%= link_to_function "Add to Bookmarks", "document.bookmarks.submit()" %>
  <%= submit_tag 'Add to Bookmarks', :class => 'hide' %>
<% end %>

app/views/catalog/_constraints_element.html.erb
<%# This view is overridden to change the alt attribute to be a title in the link_to below in order to conform to the HTML5 validity standard.  This should ultimately be fixed in Blacklight.  -%>
<%- # local params:
    # label 
    # value
    # options =>
    #   :remove => url for a remove constraint link
    #   :classes => array of classes to add to container span
    options ||= {}
    options[:escape_label] = true unless options.has_key?(:escape_label)
    options[:escape_value] = true unless options.has_key?(:escape_value)
-%>

<span class="appliedFilter constraint <%= options[:classes].join(" ") if options[:classes] %>"> 
      <%- unless label.blank? -%>
        <span class="filterName"><%= options[:escape_label] ? h(label) : label %>:</span> 
      <%- end -%>
      <%- unless value.blank? -%>
        <span class="filterValue"><%= options[:escape_value] ? h(value) : value %></span>
      <%- end -%>
</span>

app/views/catalog/_document_list.html.erb
<% # container for all documents in index view -%>
    <%= render :partial => 'catalog/_index_partials/default_group', :locals => {:docs => @response.docs.map { |x| SolrDocument.new(x) }, :facet_name => nil, :facet_value => nil} %>

app/views/catalog/_folder_control.html.erb
<%-   
  # pass in local :document with a SolrDocument
  method = (item_in_folder?(document.id) ? "delete" : "put")
  label = (item_in_folder?(document.id) ? "Unselect" : "Select")
  cssClass = (item_in_folder?(document.id) ? "deleteFolder" : "addFolder")
-%>

<%= form_tag( folder_path(document), :method => method, :class=> "folder_toggle #{cssClass}", "data-doc-id" => document.id, :title=>h(document[document_show_link_field])) do -%>  
  <%= hidden_field(:bookmark, :title, :value => document[document_show_link_field]) %>
  <%= submit_tag(label, :class=>"folder_submit", :id => "folder_submit_#{document.id}") %>
<% end %>

app/views/catalog/_home.html.erb
<%# render :partial=>'search_form' %>
<%= render :partial=>'home_text' %>

app/views/catalog/_index_default.html.erb
<%# default partial to display solr document fields in catalog index view -%>
<dl class="defList">

  <% index_fields.each do |solr_fname, field| -%>
    <% if document.has? solr_fname %>
	    <dt class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_label :field => solr_fname %></dt>
	    <dd class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_value :document => document, :field => solr_fname %></dd>
    <% end -%>
  <% end -%>

</dl>

app/views/catalog/_marc_view.html.erb
<h1>Librarian View</h1>
<div id="marc_view">
  <% fields = @document.to_marc.find_all{|f| ('000'..'999') === f.tag }  %>
  <div class="field">LEADER <%= @document.to_marc.leader %></div>
  <%- fields.each do |field| -%>
	<%- unless field.tag.to_s == "940" -%>
	  <div class="field">
	  	<div class="tag_ind">
	      <span class="tag">
	        <%= h(field.tag) %>
	  	  </span>
		  <%- if field.is_a?(MARC::ControlField) -%>
		    <span class="control_field_values">
		      <%= h(field.value) %>
		    </span>
		  <%- else -%>
		    <div class="ind1">
		      <%= !field.indicator1.blank? ? field.indicator1 : "&nbsp;&nbsp;".html_safe -%>
		    </div>
		    <div class="ind2">
		      <%= !field.indicator2.blank? ? field.indicator2 : "&nbsp;&nbsp;".html_safe -%>
		    </div>
		  </div>
		  <div class="subfields">
		    <%- field.each do |sub| -%>
			  <span class="sub_code"><%= h(sub.code) %>|</span> <%= h(sub.value) %>
			<%- end -%>
		  <%- end -%>
	    </div>
	  </div>
	<%- end-%>
  <%- end -%>
</div>

app/views/catalog/_recent_document.html.erb
    <tr>
      <% if display_thumbs %>
        <td class="span10"><%= link_to_profile recent_document.depositor("no depositor value") %> <%= render :partial => 'dashboard/_index_partials/thumbnail_display', :locals => {:document=>recent_document, :height=>60, :width=>45} %> </td>
      <% end %>
      <td>
        <h3>
          <%= link_to truncate(recent_document.title_or_label, :length => 28, :separator => ' '), sufia.generic_file_path(recent_document.noid), :title => recent_document.title_or_label  %>

          <% if display_access %>
              <% if recent_document.registered? %>
                 <span class="label label-info" title="<%=t('sufia.institution_name') %>"><%=t('sufia.institution_name') %></span>
              <% elsif recent_document.public? %>
                <span class="label label-success">Open Access</span>
              <% else %>
                <span class="label label-important">Private</span>
              <% end %>
          <% end %>
        </h3>
        <p> 
          <%= link_to truncate(recent_document.label, :length=>25),
              sufia.generic_file_path(recent_document.noid), :title => recent_document.label %><br />
          <%= link_to_facet_list(recent_document.tags, 'desc_metadata__tag', 'no keywords specified').html_safe %>
        </p>
      </td>
    </tr>

app/views/catalog/_search_form.html.erb
<%# only display the q parameter if the controller is not the dashboard.  If they are in the dashboard controller, then the search is of the dashboard. %>
<% q = params[:controller] == 'dashboard' ? nil : params[:q] %>

<%= form_tag catalog_index_path, :method => :get, :id => "search-form-header" do %>
  <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %>
            <div class="controls">
              <div class="input-append">
              <label class="accessible-hidden"><%= t('sufia.search.form.q.label') %></label> 
              <%= text_field_tag :q, q, :class => "q span50", :id => "search-field-header", :placeholder => t('sufia.search.form.q.placeholder') %><button type="submit" class="btn btn-info" id="search-submit-header"><i class="icon-search"></i> Go</button>
  <!-- <input type="submit" class="btn btn-info" id="search-submit-header" value="GO"><i class="icon-search"></i></input>
&nbsp; -->
 <%# link_to 'more options', params.merge(:controller=>"advanced", :action=>"index") , :class=>"advanced_search" if ! current_page?(advanced_path)%>
 <%# link_to 'less options', :back , :class=>"advanced_search" if current_page?(advanced_path)%>
              </div>
            </div>
<% end %>

app/views/catalog/_show_tools.html.erb
<%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark/Folder functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.
-%>
  <ul class="tools">
  
    <% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
      <li class="cite">
      <%= link_to "Cite This", citation_catalog_path(:id => @document), {:id => 'citeLink', :name => 'citation', :class => 'lightboxLink'} %>
      </li>
    <% end %>
    
    <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
      <li class="refworks">
      <%= link_to "Export to RefWorks", refworks_export_url(:id => @document) %>        
      </li>
    <% end %>
    
    <% if @document.export_formats.keys.include?( :endnote ) %>
      <li class="endnote">
        <%= link_to "Export to EndNote", catalog_path(@document, :format => 'endnote') %>
      </li>
    <% end %>
    
    <% if @document.respond_to?( :to_email_text ) %>
      <li class="email">
      <%= link_to "Email This", email_catalog_path(:id => @document), {:id => 'emailLink', :name => 'email', :class => 'lightboxLink'} %>
      </li>
    <%- end -%>
    <%- if @document.respond_to?( :to_sms_text ) -%>
      <li class="sms">
      <%= link_to "SMS This", sms_catalog_path(:id => @document), {:id => 'smsLink', :name => 'sms', :class => 'lightboxLink'} %>
      </li>
    <%- end -%>
    
    <% if @document.respond_to?(:to_marc) %>
      <li class="librarian_view">
        <%= link_to "Librarian View", librarian_view_catalog_path(@document), {:id => 'librarianLink', :name => 'librarian_view', :class => 'lightboxLink'} %>
      </li>
    <% end %>
    
  </ul>

app/views/catalog/_sort_and_per_page.html.erb
<% unless @response.response['numFound'] < 2 %>
    <%-# kind of hacky way to get this to work on catalog and folder controllers.  May be able to simple do {:action=>"index"} but I'm not sure -%>
    <%= form_tag params[:controller] == "folder" ? folder_index_path : catalog_index_path, :method => :get, :class => "well form-inline" do %>
  <div class="sorting">
      <%= label_tag(:sort, "<strong>Sort by</strong> ".html_safe) %>
      <%= select_tag(:sort, options_for_select(sort_fields, h(params[:sort])), :class => "input-medium") %>

      <%= label_tag(:per_page) do %>
        <strong>Show</strong> <%= select_tag(:per_page, options_for_select(['10', '20', '50', '100'], h(params[:per_page])), :title => "Number of results to display per page", :class => "input-small")  %> per page
        <% end %>
      <%= search_as_hidden_fields(:omit_keys => [:per_page, :sort]) %>
      <button class="btn btn-primary"><i class="icon-refresh"></i> Refresh</button>

  </div>
    <% end %>
<% end %>

app/views/catalog/endnote.endnote.erb
<%= render_endnote_texts(@documents) %>

app/views/catalog/librarian_view.html.erb
<%- if @document.respond_to?(:to_marc) -%>
  <%= render "marc_view" %>
<%- end -%>

app/views/catalog/sms.erb
<%= render :partial => 'sms_form' %>